BEGIN;

DROP TABLE person CASCADE;
DROP TABLE action CASCADE;
DROP TABLE thought CASCADE;
DROP TABLE astronaut CASCADE;
DROP TABLE location CASCADE;
DROP TABLE spaceship CASCADE;
DROP TABLE flight CASCADE;
DROP TABLE flight_astronaut CASCADE;
DROP TYPE SEX;
DROP TYPE KIND;

COMMIT;